// Code generated by "stringer -type=EncodingType"; DO NOT EDIT.

package vnc

import "fmt"

const (
	_EncodingType_name_0 = "EncColorPseudo"
	_EncodingType_name_1 = "EncDesktopSizePseudo"
	_EncodingType_name_2 = "EncRawEncCopyRectEncRRE"
	_EncodingType_name_3 = "EncHextile"
	_EncodingType_name_4 = "EncTRLEEncZRLE"
)

var (
	_EncodingType_index_0 = [...]uint8{0, 14}
	_EncodingType_index_1 = [...]uint8{0, 20}
	_EncodingType_index_2 = [...]uint8{0, 6, 17, 23}
	_EncodingType_index_3 = [...]uint8{0, 10}
	_EncodingType_index_4 = [...]uint8{0, 7, 14}
)

func (i EncodingType) String() string {
	switch {
	case i == -239:
		return _EncodingType_name_0
	case i == -223:
		return _EncodingType_name_1
	case 0 <= i && i <= 2:
		return _EncodingType_name_2[_EncodingType_index_2[i]:_EncodingType_index_2[i+1]]
	case i == 5:
		return _EncodingType_name_3
	case 15 <= i && i <= 16:
		i -= 15
		return _EncodingType_name_4[_EncodingType_index_4[i]:_EncodingType_index_4[i+1]]
	default:
		return fmt.Sprintf("EncodingType(%d)", i)
	}
}
