// Code generated by "stringer -type=EncodingType"; DO NOT EDIT.

package vnc

import "fmt"

const _EncodingType_name = "EncContinuousUpdatesPseudoEncFencePseudoEncClientRedirectEncXvpPseudoEncExtendedDesktopSizePseudoEncDesktopNamePseudoEncTightPngEncQEMUExtendedKeyEventPseudoEncQEMUPointerMotionChangePseudoEncCompressionLevel1EncCompressionLevel2EncCompressionLevel3EncCompressionLevel4EncCompressionLevel5EncCompressionLevel6EncCompressionLevel7EncCompressionLevel8EncCompressionLevel9EncCompressionLevel10EncXCursorPseudoEncColorPseudoEncLastRectPseudoEncDesktopSizePseudoEncJPEGQualityLevelPseudo1EncJPEGQualityLevelPseudo2EncJPEGQualityLevelPseudo3EncJPEGQualityLevelPseudo4EncJPEGQualityLevelPseudo5EncJPEGQualityLevelPseudo6EncJPEGQualityLevelPseudo7EncJPEGQualityLevelPseudo8EncJPEGQualityLevelPseudo9EncJPEGQualityLevelPseudo10EncRawEncCopyRectEncRREEncCoRREEncHextileEncZlibEncTightEncZlibHexEncUltra1EncUltra2EncTRLEEncZRLEEncJPEGEncJRLE"

var _EncodingType_map = map[EncodingType]string{
	-313: _EncodingType_name[0:26],
	-312: _EncodingType_name[26:40],
	-311: _EncodingType_name[40:57],
	-309: _EncodingType_name[57:69],
	-308: _EncodingType_name[69:97],
	-307: _EncodingType_name[97:117],
	-260: _EncodingType_name[117:128],
	-258: _EncodingType_name[128:157],
	-257: _EncodingType_name[157:189],
	-256: _EncodingType_name[189:209],
	-255: _EncodingType_name[209:229],
	-254: _EncodingType_name[229:249],
	-253: _EncodingType_name[249:269],
	-252: _EncodingType_name[269:289],
	-251: _EncodingType_name[289:309],
	-250: _EncodingType_name[309:329],
	-249: _EncodingType_name[329:349],
	-248: _EncodingType_name[349:369],
	-247: _EncodingType_name[369:390],
	-240: _EncodingType_name[390:406],
	-239: _EncodingType_name[406:420],
	-224: _EncodingType_name[420:437],
	-223: _EncodingType_name[437:457],
	-32:  _EncodingType_name[457:483],
	-31:  _EncodingType_name[483:509],
	-30:  _EncodingType_name[509:535],
	-29:  _EncodingType_name[535:561],
	-28:  _EncodingType_name[561:587],
	-27:  _EncodingType_name[587:613],
	-26:  _EncodingType_name[613:639],
	-25:  _EncodingType_name[639:665],
	-24:  _EncodingType_name[665:691],
	-23:  _EncodingType_name[691:718],
	0:    _EncodingType_name[718:724],
	1:    _EncodingType_name[724:735],
	2:    _EncodingType_name[735:741],
	4:    _EncodingType_name[741:749],
	5:    _EncodingType_name[749:759],
	6:    _EncodingType_name[759:766],
	7:    _EncodingType_name[766:774],
	8:    _EncodingType_name[774:784],
	9:    _EncodingType_name[784:793],
	10:   _EncodingType_name[793:802],
	15:   _EncodingType_name[802:809],
	16:   _EncodingType_name[809:816],
	21:   _EncodingType_name[816:823],
	22:   _EncodingType_name[823:830],
}

func (i EncodingType) String() string {
	if str, ok := _EncodingType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("EncodingType(%d)", i)
}
