// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package vnc

import "fmt"

const (
	_MessageType_name_0 = "SetPixelFormatMsgTypeSetColorMapEntriesMsgTypeSetEncodingsMsgTypeFramebufferUpdateRequestMsgTypeKeyEventMsgTypePointerEventMsgTypeClientCutTextMsgType"
	_MessageType_name_1 = "AteniKVMKeepAliveEventMsgType"
	_MessageType_name_2 = "AteniKVMVideoGetInfoMsgType"
	_MessageType_name_3 = "AteniKVMMouseGetInfoMsgType"
	_MessageType_name_4 = "AteniKVMSessionMessageMsgType"
	_MessageType_name_5 = "AteniKVMGetViewerLangMsgType"
)

var (
	_MessageType_index_0 = [...]uint8{0, 21, 46, 65, 96, 111, 130, 150}
	_MessageType_index_1 = [...]uint8{0, 29}
	_MessageType_index_2 = [...]uint8{0, 27}
	_MessageType_index_3 = [...]uint8{0, 27}
	_MessageType_index_4 = [...]uint8{0, 29}
	_MessageType_index_5 = [...]uint8{0, 28}
)

func (i MessageType) String() string {
	switch {
	case 0 <= i && i <= 6:
		return _MessageType_name_0[_MessageType_index_0[i]:_MessageType_index_0[i+1]]
	case i == 22:
		return _MessageType_name_1
	case i == 51:
		return _MessageType_name_2
	case i == 55:
		return _MessageType_name_3
	case i == 57:
		return _MessageType_name_4
	case i == 60:
		return _MessageType_name_5
	default:
		return fmt.Sprintf("MessageType(%d)", i)
	}
}
