// Code generated by "stringer -type=SecurityType"; DO NOT EDIT.

package vnc2webm

import "fmt"

const (
	_SecurityType_name_0 = "SecTypeUnknownSecTypeNoneSecTypeVNC"
	_SecurityType_name_1 = "SecTypeTight"
	_SecurityType_name_2 = "SecTypeVeNCrypt"
)

var (
	_SecurityType_index_0 = [...]uint8{0, 14, 25, 35}
	_SecurityType_index_1 = [...]uint8{0, 12}
	_SecurityType_index_2 = [...]uint8{0, 15}
)

func (i SecurityType) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _SecurityType_name_0[_SecurityType_index_0[i]:_SecurityType_index_0[i+1]]
	case i == 16:
		return _SecurityType_name_1
	case i == 19:
		return _SecurityType_name_2
	default:
		return fmt.Sprintf("SecurityType(%d)", i)
	}
}
