// Code generated by "stringer -type=SecuritySubType"; DO NOT EDIT.

package vnc2webm

import "fmt"

const (
	_SecuritySubType_name_0 = "SecSubTypeUnknown"
	_SecuritySubType_name_1 = "SecSubTypeVeNCrypt01PlainSecSubTypeVeNCrypt01TLSNoneSecSubTypeVeNCrypt01TLSVNCSecSubTypeVeNCrypt01TLSPlainSecSubTypeVeNCrypt01X509NoneSecSubTypeVeNCrypt01X509VNCSecSubTypeVeNCrypt01X509Plain"
	_SecuritySubType_name_2 = "SecSubTypeVeNCrypt02PlainSecSubTypeVeNCrypt02TLSNoneSecSubTypeVeNCrypt02TLSVNCSecSubTypeVeNCrypt02TLSPlainSecSubTypeVeNCrypt02X509NoneSecSubTypeVeNCrypt02X509VNCSecSubTypeVeNCrypt02X509Plain"
)

var (
	_SecuritySubType_index_0 = [...]uint8{0, 17}
	_SecuritySubType_index_1 = [...]uint8{0, 25, 52, 78, 106, 134, 161, 190}
	_SecuritySubType_index_2 = [...]uint8{0, 25, 52, 78, 106, 134, 161, 190}
)

func (i SecuritySubType) String() string {
	switch {
	case i == 0:
		return _SecuritySubType_name_0
	case 19 <= i && i <= 25:
		i -= 19
		return _SecuritySubType_name_1[_SecuritySubType_index_1[i]:_SecuritySubType_index_1[i+1]]
	case 256 <= i && i <= 262:
		i -= 256
		return _SecuritySubType_name_2[_SecuritySubType_index_2[i]:_SecuritySubType_index_2[i+1]]
	default:
		return fmt.Sprintf("SecuritySubType(%d)", i)
	}
}
