// Code generated by "stringer -type=ServerMessageType"; DO NOT EDIT.

package vnc

import "fmt"

const (
	_ServerMessageType_name_0 = "FramebufferUpdateMsgTypeSetColorMapEntriesMsgTypeBellMsgTypeServerCutTextMsgTypeAteniKVMFrontGroundEventMsgType"
	_ServerMessageType_name_1 = "AteniKVMKeepAliveEventMsgType"
	_ServerMessageType_name_2 = "AteniKVMVideoGetInfoMsgType"
	_ServerMessageType_name_3 = "AteniKVMMouseGetInfoMsgType"
	_ServerMessageType_name_4 = "AteniKVMSessionMessageMsgType"
	_ServerMessageType_name_5 = "AteniKVMGetViewerLangMsgType"
)

var (
	_ServerMessageType_index_0 = [...]uint8{0, 24, 49, 60, 80, 111}
	_ServerMessageType_index_1 = [...]uint8{0, 29}
	_ServerMessageType_index_2 = [...]uint8{0, 27}
	_ServerMessageType_index_3 = [...]uint8{0, 27}
	_ServerMessageType_index_4 = [...]uint8{0, 29}
	_ServerMessageType_index_5 = [...]uint8{0, 28}
)

func (i ServerMessageType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _ServerMessageType_name_0[_ServerMessageType_index_0[i]:_ServerMessageType_index_0[i+1]]
	case i == 22:
		return _ServerMessageType_name_1
	case i == 51:
		return _ServerMessageType_name_2
	case i == 55:
		return _ServerMessageType_name_3
	case i == 57:
		return _ServerMessageType_name_4
	case i == 60:
		return _ServerMessageType_name_5
	default:
		return fmt.Sprintf("ServerMessageType(%d)", i)
	}
}
