// Code generated by "stringer -type=TightCompression"; DO NOT EDIT.

package vnc

import "fmt"

const (
	_TightCompression_name_0 = "TightCompressionBasic"
	_TightCompression_name_1 = "TightCompressionFillTightCompressionJPEGTightCompressionPNG"
)

var (
	_TightCompression_index_0 = [...]uint8{0, 21}
	_TightCompression_index_1 = [...]uint8{0, 20, 40, 59}
)

func (i TightCompression) String() string {
	switch {
	case i == 0:
		return _TightCompression_name_0
	case 8 <= i && i <= 10:
		i -= 8
		return _TightCompression_name_1[_TightCompression_index_1[i]:_TightCompression_index_1[i+1]]
	default:
		return fmt.Sprintf("TightCompression(%d)", i)
	}
}
