// Code generated by "stringer -type=TightFilter"; DO NOT EDIT.

package vnc2video

import "fmt"

const _TightFilter_name = "TightFilterCopyTightFilterPaletteTightFilterGradient"

var _TightFilter_index = [...]uint8{0, 15, 33, 52}

func (i TightFilter) String() string {
	if i >= TightFilter(len(_TightFilter_index)-1) {
		return fmt.Sprintf("TightFilter(%d)", i)
	}
	return _TightFilter_name[_TightFilter_index[i]:_TightFilter_index[i+1]]
}
